import React from 'react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, fireEvent, waitFor } from '@testing-library/react-native';

import * as fixtures from './support/fixtures';
import type { RecoveryNotificationPreference } from '../../src/lib/types';

/**
 * Rendered coverage for the Recovery Target notification preferences screen
 * — Recovery Target Improvement Plan §7.5/§10.8/§11 Phase 6.
 *
 * Follows the same mocking shape as operatingSchedule.test.tsx: useFocusEffect
 * stands in for a mount effect since there is no NavigationContainer in this
 * harness, and api.get/api.put are routed by path.
 */

const apiGet = vi.fn();
const apiPut = vi.fn();

vi.mock('@react-navigation/native', () => ({
  useFocusEffect: (effect: () => void | (() => void)) => {
    React.useEffect(() => effect(), [effect]);
  },
}));

vi.mock('../../src/lib/api', () => ({
  api: {
    get: (...args: unknown[]) => apiGet(...args),
    put: (...args: unknown[]) => apiPut(...args),
    post: vi.fn(),
    patch: vi.fn(),
    delete: vi.fn(),
  },
  errorMessage: (err: unknown) => (err instanceof Error ? err.message : 'Something went wrong.'),
  ApiError: class ApiError extends Error {},
}));

vi.mock('../../src/context/BusinessProfileContext', () => ({
  useBusinessProfiles: () => ({
    profiles: [fixtures.businessProfile],
    selected: fixtures.businessProfile,
    categories: fixtures.categories,
    loading: false,
    error: null,
    selectProfile: vi.fn(),
    refresh: vi.fn(),
    refreshCategories: vi.fn(),
    createCategory: vi.fn(),
  }),
  BusinessProfileProvider: ({ children }: { children: React.ReactNode }) => children,
}));

const DEFAULT_PREFERENCE: RecoveryNotificationPreference = {
  targetIncreaseAlertEnabled: true,
  targetIncreaseThresholdPercent: 15,
  behindThreeDaysAlertEnabled: true,
  openDayNoSalesAlertEnabled: true,
  projectionShortfallAlertEnabled: true,
  coverageReachedAlertEnabled: true,
  quietHoursStart: null,
  quietHoursEnd: null,
  minHoursBetweenNotifications: 24,
};

async function renderScreen(preference: RecoveryNotificationPreference = DEFAULT_PREFERENCE) {
  apiGet.mockImplementation((path: string) => {
    if (path.endsWith('/recovery-notification-preferences')) return Promise.resolve(preference);
    return Promise.reject(new Error(`unexpected path ${path}`));
  });
  const { RecoveryNotificationPreferencesScreen } = await import(
    '../../src/screens/RecoveryNotificationPreferencesScreen'
  );
  const { ThemeProvider } = await import('../../src/context/ThemeContext');
  return render(
    <ThemeProvider initialMode="light">
      <RecoveryNotificationPreferencesScreen />
    </ThemeProvider>,
  );
}

beforeEach(() => {
  apiGet.mockReset();
  apiPut.mockReset();
  apiPut.mockImplementation((_path: string, body: unknown) =>
    Promise.resolve({ ...DEFAULT_PREFERENCE, ...(body as object) }),
  );
});

describe('RecoveryNotificationPreferencesScreen — defaults', () => {
  it('renders the server defaults: all five toggles on, 15% threshold, no quiet hours, 24h cooldown', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    expect(queries.getByRole('switch', { name: /Target increased beyond a threshold/ }).props.accessibilityState.checked).toBe(true);
    expect(queries.getByRole('switch', { name: /Behind pace for three days/ }).props.accessibilityState.checked).toBe(true);
    expect(queries.getByRole('switch', { name: /Open day ending with no sales \(Coming soon\)/ }).props.accessibilityState.checked).toBe(true);
    expect(queries.getByRole('switch', { name: /Projection crosses to shortfall \(Coming soon\)/ }).props.accessibilityState.checked).toBe(true);
    expect(queries.getByRole('switch', { name: /Monthly target reached/ }).props.accessibilityState.checked).toBe(true);

    expect(queries.getByLabelText('Threshold percent')).toHaveProp('value', '15');
    expect(queries.getByLabelText('Hours between notifications')).toHaveProp('value', '24');
    expect(queries.getByLabelText('Quiet hours start')).toHaveProp('value', '');
    expect(queries.getByLabelText('Quiet hours end')).toHaveProp('value', '');
  });

  it('marks the two unimplemented triggers as not currently doing anything', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');
    expect(
      queries.getAllByText(/Not active yet — this alert isn't generated by FinSight today/).length,
    ).toBe(2);
    expect(
      await queries.findByText(/Two of the alerts above are coming soon and don't do anything yet/),
    ).toBeTruthy();
  });
});

describe('RecoveryNotificationPreferencesScreen — save', () => {
  it('persists a toggle change and the threshold percent via PUT', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    await fireEvent.press(queries.getByRole('switch', { name: /Behind pace for three days/ }));
    await fireEvent.changeText(queries.getByLabelText('Threshold percent'), '25');
    await fireEvent.press(queries.getByRole('button', { name: 'Save preferences' }));

    await waitFor(() => expect(apiPut).toHaveBeenCalled());
    const [path, body] = apiPut.mock.calls[0];
    expect(path).toBe(`/business-profiles/${fixtures.businessProfile.id}/recovery-notification-preferences`);
    expect(body).toMatchObject({
      behindThreeDaysAlertEnabled: false,
      targetIncreaseThresholdPercent: 25,
    });
    expect(await queries.findByText('Saved.')).toBeTruthy();
  });

  it('rejects a threshold percent outside 1-100 before calling the server', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    await fireEvent.changeText(queries.getByLabelText('Threshold percent'), '150');
    await fireEvent.press(queries.getByRole('button', { name: 'Save preferences' }));

    expect(await queries.findByText('Enter a percentage between 1 and 100.')).toBeTruthy();
    expect(apiPut).not.toHaveBeenCalled();
  });

  it('rejects an hours-between value outside 1-168 before calling the server', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    await fireEvent.changeText(queries.getByLabelText('Hours between notifications'), '200');
    await fireEvent.press(queries.getByRole('button', { name: 'Save preferences' }));

    expect(await queries.findByText('Enter a whole number of hours between 1 and 168.')).toBeTruthy();
    expect(apiPut).not.toHaveBeenCalled();
  });

  it('rejects setting only one quiet-hours time — both or neither', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    await fireEvent.changeText(queries.getByLabelText('Quiet hours start'), '21:00');
    await fireEvent.press(queries.getByRole('button', { name: 'Save preferences' }));

    expect(
      await queries.findByText('Set both a start and an end time for quiet hours, or leave both blank.'),
    ).toBeTruthy();
    expect(apiPut).not.toHaveBeenCalled();
  });

  it('accepts both quiet-hours times set together and saves them', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    await fireEvent.changeText(queries.getByLabelText('Quiet hours start'), '21:00');
    await fireEvent.changeText(queries.getByLabelText('Quiet hours end'), '07:00');
    await fireEvent.press(queries.getByRole('button', { name: 'Save preferences' }));

    await waitFor(() => expect(apiPut).toHaveBeenCalled());
    const [, body] = apiPut.mock.calls[0];
    expect(body).toMatchObject({ quietHoursStart: '21:00', quietHoursEnd: '07:00' });
  });

  it('rejects an invalid time shape for a quiet-hours field', async () => {
    const queries = await renderScreen();
    await queries.findByText('Notification settings');

    await fireEvent.changeText(queries.getByLabelText('Quiet hours start'), '21:00');
    await fireEvent.changeText(queries.getByLabelText('Quiet hours end'), 'not a time');
    await fireEvent.press(queries.getByRole('button', { name: 'Save preferences' }));

    expect(await queries.findByText('Enter a time as HH:MM, e.g. 21:00.')).toBeTruthy();
    expect(apiPut).not.toHaveBeenCalled();
  });
});
